[SERVICE]
    Flush         5
    Daemon        Off
    Log_Level     info
    Parsers_File  parsers.conf

[INPUT]
    Name          tail
    Tag           syslog
    Path          /var/log/syslog
    DB            /fluent-bit/db/syslog.db
    Read_from_Head True
    Skip_Long_Lines On

[INPUT]
    Name          tail
    Tag           kern
    Path          /var/log/kern.log
    DB            /fluent-bit/db/kern.db
    Read_from_Head True
    Skip_Long_Lines On

[FILTER]
    Name          record_modifier
    Match         *
    Record        host ${HOSTNAME}

[OUTPUT]
    Name          opensearch
    Match         *
    Host          opensearch-1
    Port          9200
    Index         ubuntu-logs
    Suppress_Type_Name On
    Buffer_Size   False
    tls           Off
    tls.verify    Off
